# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(choices=[(1, 'Normal'), (9, 'Admin')]),
        ),
    ]
